version: 2.1
jobs:
  build:
    docker:
      - image: rust
        environment:
          DATABASE_URL: test.sqlite3
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
      - run: cargo install diesel_cli
      - run: diesel setup
      - run: cargo test
